/// Flutter icons ScannerIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ScannerIcon
///      fonts:
///       - asset: fonts/ScannerIcon.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class ScannerIcon {
  ScannerIcon._();

  static const _kFontFam = 'ScannerIcon';
  static const _kFontPkg = null;

  static const IconData guidedog = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pool = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData perm_phone_msg = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ac_unit = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_bar = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beach_access = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData free_breakfast = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fitness_center = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hot_tub = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData child_care = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_laundry_service = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_parking = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData restaurant = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData room_service = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smoke_free = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spa = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData live_tv = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun = IconData(0xf185, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sliders = IconData(0xf1de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bed = IconData(0xf236, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData address_book = IconData(0xf2b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car_side = IconData(0xf5e4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
